## 1) Vectorized operations
All numpy operations are vectorized, where the operations can be applied to the whole array instead of on each element individually.

In [2]:
#Simple calculations with scalars and Numpy Arrays
import numpy as np
x = np.array([1,2,3,4])
# Add 1 to each element in array
y = x + 1 # All the elements in the array are added by 1 simultaneously
print(f"x + 1 is {y}")
z = x * y
print(f"x multiplied by y is {z}")

x + 1 is [2 3 4 5]
x multiplied by y is [ 2  6 12 20]


<ul>
    <li>Two Numpy Arrays are multiplied element by element</li>
    <li>Arithmetic operations between two NumPy Arrays are not matrix multiplications</li>
    <li>A matrix multiplication in NumPy will use numpy.dot()</li>

In [3]:
print(f"Dot product of x and y is {np.dot(x,y)}")

Dot product of x and y is 40


In [5]:
# Comparing two numpy arrays
x == y

array([False, False, False, False])

## 2) Universal functions (ufuncs)
Numpy has many universal functions we can use them to eliminate as many loops to optimize the code. Ufuncs have a pretty good coverage in math, trigonometry, summary statistics, and comparison operations.

In [7]:
# Basic functions
x = np.arange(5, 10)
print(f"x is {x}")
print(f"Square of x is {np.square(x)}")
y = np.ones(5) * 10
print(f"y is {y}")
print(f"y mod x is {np.mod(y, x)}")

x is [5 6 7 8 9]
Square of x is [25 36 49 64 81]
y is [10. 10. 10. 10. 10.]
y mod x is [0. 4. 3. 2. 1.]


In [12]:
# More advanced functions
print(f"x is {x}")
z = np.repeat(x, 3) # Repeats each element in x three times
print(f"z is {z}") 
z = np.repeat(x, 3).reshape(5, 3) # Reshapes the resulting array into 5, 3 dimensions
print(f"z is now {z}")
print(f"Median of z along 0 axis is {np.median(z, axis=0)}")
print(f"Median of z along 1 axis is {np.median(z, axis=1)}")
print(f"Median of z is {np.median(z)}")

x is [5 6 7 8 9]
z is [5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]
z is now [[5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]
Median of z along 0 axis is [7. 7. 7.]
Median of z along 1 axis is [5. 6. 7. 8. 9.]
Median of z is 7.0


In [13]:
# ufuncs not only provide optional arguments to tune operations, they also provide some built-in methods
# Accumulate the result of applying add()
print(f"x is {x}")
print(f"Add accumulator of x is {np.add.accumulate(x)}")

x is [5 6 7 8 9]
Add accumulator of x is [ 5 11 18 26 35]


## 3) Broadcasting and shape manipulation
Numpy operations are mostly done element-wise, which requires two arrays in an operation to have the same shape. But, this doesn't mean that NumPy operations can't take two differently shaped arrays. NumPy provides the flexibility to broadcast a smaller-sized array across a larger one. 
Not all array sizes are compatible with broadcasting, there are certain rules as shown below:
<ul>
    <li>Two arrays should be of equal dimensions</li>
    <li>One of the array is 1</li>

In [15]:
x = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20]])
y = np.array([1,2,3])
print(f"x + y is {x + y}")

x + y is [[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In the above example, x has a shape of (3,3), y has shape of 3, but in NumPy broadcasting, the shape of y is translated to (3,1). So the second condition of the rule has been met, y has been broadcast to the same shape of x by repeating it.

In [16]:
# Reshaping NumPy Arrays
x = np.arange(24)
x.shape = 2, 3, -1
print(f"x is {x}")

x is [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [18]:
# Vector Stacking
x = np.arange(0, 10, 2)
y = np.arange(0, -5, -1) # x and y are two equally-sized row vectors
print(f"x over y vertical stacked is {np.vstack([x, y])}")
print(f"x over y horizontal stacked is {np.hstack([x, y])}")
print(f"x over y diagonal stacked is {np.dstack([x, y])}")

x over y vertical stacked is [[ 0  2  4  6  8]
 [ 0 -1 -2 -3 -4]]
x over y horizontal stacked is [ 0  2  4  6  8  0 -1 -2 -3 -4]
x over y diagonal stacked is [[[ 0  0]
  [ 2 -1]
  [ 4 -2]
  [ 6 -3]
  [ 8 -4]]]


In [19]:
# Boolean mask
x = np.array([1,3,-1,5,7,-1])
mask = (x < 0)
print(mask)

[False False  True False False  True]
