Numpy provides different types of objects to solve mathematical problems.

## 1) Matrix and vector operations

In [1]:
import numpy as np

In [2]:
# Create numpy matrices
ndArray = np.arange(9).reshape(3,3)
x = np.matrix(ndArray)
y = np.mat(np.identity(3))
print(f"x is {x}")
print(f"y is {y}")

x is [[0 1 2]
 [3 4 5]
 [6 7 8]]
y is [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
