Numpy provides different types of objects to solve mathematical problems.

## 1) Matrix and vector operations

In [2]:
import numpy as np

In [3]:
# Create numpy matrices
ndArray = np.arange(9).reshape(3,3)
x = np.matrix(ndArray)
y = np.mat(np.identity(3))
print(f"x is {x}")
print(f"y is {y}")

x is [[0 1 2]
 [3 4 5]
 [6 7 8]]
y is [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Sum of two matrices
print(f"Sum of matrix x and matrix y is {x + y}")

Sum of matrix x and matrix y is [[1. 1. 2.]
 [3. 5. 5.]
 [6. 7. 9.]]


In [7]:
# Product of two matrices
print(f"Product of matrix x and matrix y is {x @ y}")

Product of matrix x and matrix y is [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [10]:
# Inverse of matrix
x = np.matrix(np.random.random_integers(1, 50, 9).reshape(3,3))
print(f"Inverse of matrix {x} is {x.I}")

Inverse of matrix [[ 9 25 28]
 [22 38 24]
 [41 48 20]] is [[ 0.09839357 -0.21184739  0.11646586]
 [-0.13654618  0.24297189 -0.10040161]
 [ 0.12600402 -0.14884538  0.05220884]]


c:\users\jv152\ideaprojects\numpyguide\venv\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 50 + 1) instead
  


In [12]:
# Solving linear equation Ax = b, x = Inverse(A).b
A = np.mat('3 1 4; 1 5 9; 2 6 5')
b = np.mat([[1], [2], [3]])
x = A.I @ b
print(x)
# Evaluate Ax = b equation
print(np.allclose(A @ x, b))

[[ 0.26666667]
 [ 0.46666667]
 [-0.06666667]]
True


## 2) Linear Algebra in Numpy

In [14]:
# Dot product of two vectors
x = np.array([[1, 2], [3, 4]])
y = np.array([[10, 20], [30, 40]])
print(f"Dot product of x and y is \n {np.dot(x, y)}")

Dot product of x and y is 
 [[ 70 100]
 [150 220]]


In [15]:
# VDot product of two vectors, returns the sum of multiplication of corresponding elements in both matrices
print(f"VDot product of x and y is {np.vdot(x, y)}")

VDot product of x and y is 300


In [18]:
# Numpy.outer() function is the outer product of two vectors. It flattens the input arrays if they are not one-dimensional.
# If a flattened input vector A has shape (M, ) and the flattened input vector B has shape (N, ), then the result shape would be (M, N)
print(f"Shape of x is {x.shape}")
print(f"Shape of x is {y.shape}")
print(f"Outer product of x and y is \n {np.outer(x, y)}")

Shape of x is (2, 2)
Shape of x is (2, 2)
Outer product of x and y is 
 [[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]
 [ 40  80 120 160]]
